# Generated by Django 5.2.7 on 2025-10-29 15:24

from django.db import migrations
from django.contrib.auth.models import User

def create_admin_user(apps, schema_editor):
    User = apps.get_model('auth', 'User')
    if not User.objects.filter(username='admin').exists():
        User.objects.create_superuser(
            username='admin',
            email='admin@example.com', 
            password='admin123'
        )

class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_admin_user),
    ]