# Generated by Django 5.2.7 on 2026-01-12 22:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='employee_type',
            field=models.CharField(blank=True, choices=[('JUNIOR', 'Junior (стаж < 2 лет)'), ('MIDDLE', 'Middle (стаж 2-5 лет)'), ('SENIOR', 'Senior (стаж > 5 лет)'), ('LEAD', 'Team Lead'), ('MANAGER', 'Менеджер'), ('OTHER', 'Другое')], help_text='Выберите уровень или оставьте пустым для автоопределения', max_length=20, null=True, verbose_name='Уровень сотрудника'),
        ),
        migrations.AddField(
            model_name='product',
            name='position',
            field=models.CharField(blank=True, help_text='Например: Разработчик, Менеджер, Аналитик', max_length=100, null=True, verbose_name='Должность'),
        ),
        migrations.AddField(
            model_name='purchase',
            name='payment_type',
            field=models.CharField(blank=True, choices=[('SALARY', 'Зарплата'), ('BONUS', 'Премия'), ('ADVANCE', 'Аванс'), ('VACATION', 'Отпускные'), ('SICK_LEAVE', 'Больничный'), ('MATERNITY', 'Декретные'), ('OTHER', 'Другое')], default='SALARY', max_length=20, null=True, verbose_name='Тип выплаты'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=100, verbose_name='ФИО сотрудника'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Оклад'),
        ),
        migrations.AlterField(
            model_name='product',
            name='quantity',
            field=models.PositiveIntegerField(default=1, verbose_name='Стаж (лет)'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='address',
            field=models.CharField(help_text='Например: Зарплата за январь, Премия за проект', max_length=200, verbose_name='Описание выплаты'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата выплаты'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='person',
            field=models.CharField(help_text='Введите сумму премии в рублях', max_length=200, verbose_name='Сумма премии'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.product', verbose_name='Сотрудник'),
        ),
    ]
