# Generated by Django 5.2.7 on 2025-11-06 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_fix_database'),
    ]

    operations = [
    ]
